// ─────────────────────────────────────────────────────────────────────────────
// Pin definitions for LCDWIKI 2.8" ESP32-S3 Display (ES3C28P / ES3N28P)
// https://www.lcdwiki.com/2.8inch_ESP32-S3_Display
// ─────────────────────────────────────────────────────────────────────────────
// NOTE: The old INMP441 / MAX98357A pin definitions are WRONG for this board.
// This board has an onboard ES8311 audio codec wired to the pins below.
// ─────────────────────────────────────────────────────────────────────────────

// ── Audio: ES8311 codec (I2S) ────────────────────────────────────────────────
#define AUDIO_ENABLE    1    // Low = speaker amp enabled (FM8002E enable pin)
#define I2S_MCLK        4    // Master clock (generated by ESP32-S3)
#define I2S_BCLK        5    // Bit clock
#define I2S_DOUT        8    // ESP32 → ES8311 → speaker (DAC output)
#define I2S_LRCK        7    // Left/Right clock (LRCK / WS)
#define I2S_DIN         6    // ES8311 → ESP32 (ADC input from mic)

// ── ES8311 codec config (I2C, shared with touch screen) ─────────────────────
#define CODEC_I2C_SDA   16   // Shared with FT6336G touch IC
#define CODEC_I2C_SCL   15   // Shared with FT6336G touch IC
#define ES8311_ADDR     0x18 // ES8311 I2C address (ADDR pin pulled low)

// ── Display: ILI9341 (SPI) ───────────────────────────────────────────────────
#define LCD_CS          10
#define LCD_DC          46
#define LCD_CLK         12
#define LCD_MOSI        11
#define LCD_MISO        13
#define LCD_BL          45   // Backlight (HIGH = on)

// ── Touch screen: FT6336G (I2C, same bus as codec) ──────────────────────────
#define TOUCH_SDA       16   // Same as CODEC_I2C_SDA
#define TOUCH_SCL       15   // Same as CODEC_I2C_SCL
#define TOUCH_RST       18
#define TOUCH_INT       17

// ── RGB LED (WS2812 single-wire) ─────────────────────────────────────────────
#define RGB_LED         42

// ── Push-to-talk button (on IO2/IO3/IO14/IO21 expansion header) ──────────────
#define BTN_RECORD      3    // IO3 — INPUT_PULLUP, reads button state (active LOW)
#define BTN_GND         2    // IO2 — OUTPUT LOW, acts as GND for the button
                             // Wire the button between IO2 and IO3.
                             // IO43 (UART RX) and IO44 (UART TX) are unusable:
                             // UART TX idles HIGH; UART peripheral holds RX.

// ── SD card (SDIO) ───────────────────────────────────────────────────────────
#define SD_CLK          38
#define SD_CMD          40
#define SD_DATA0        39
#define SD_DATA1        41
#define SD_DATA2        48
#define SD_DATA3        47

// ── Battery ADC ─────────────────────────────────────────────────────────────
#define BATTERY_ADC     9

// ── UART (debug / external serial) ─────────────────────────────────────────
#define UART_RX         43
#define UART_TX         44

// ── Free expand pins ────────────────────────────────────────────────────────
// IO2  → available
// IO3  → available
// IO14 → available
// IO21 → available
