// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABxr5DlWydIXW7EBHk7nYh2r3qlf4df_I',
    appId: '1:233818904977:web:76839d8d4143d89d616230',
    messagingSenderId: '233818904977',
    projectId: 'llm-tutor-d721e',
    authDomain: 'llm-tutor-d721e.firebaseapp.com',
    storageBucket: 'llm-tutor-d721e.firebasestorage.app',
    measurementId: 'G-FT169NX7GB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD71FKbTF6s2rOWFTJqwzmvZEzsC-B_I64',
    appId: '1:233818904977:android:39f93f9f9d649b0f616230',
    messagingSenderId: '233818904977',
    projectId: 'llm-tutor-d721e',
    storageBucket: 'llm-tutor-d721e.firebasestorage.app',
  );
}
